---
title: "PREDICCIÓN ACCIDENTES MEDELLIN"
author: "Edwin Villarraga"
date: "16/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# DESCRIPCIÓN DEL PROBLEMA


# HIPOTESIS


# CARGA Y DEPURACION DE DATOS

## Carga de Datos

### Datos de 2014

```{r}
raw_data_2014 <- read.csv(file="./data/Accidentalidad_georreferenciada_2014.csv", encoding="UTF-8", header=TRUE, sep=",")
```


```{r}
head(raw_data_2014)
```

```{r}
summary(raw_data_2014)
```

```{r}
str(raw_data_2014)
```


```{r}
levels(raw_data_2014$CLASE)
```

```{r}
levels(raw_data_2014$CLASE) <- c("Atropello","Caida_Ocupante","Choque","Incendio","Otro",
                                 "Volcamiento")
```

```{r}
levels(raw_data_2014$CLASE)
```

### Datos de 2015

```{r}
raw_data_2015 <- read.csv(file="./data/Accidentalidad_georreferenciada_2015.csv", encoding="UTF-8", header=TRUE, sep=",")
```


```{r}
head(raw_data_2015)
```

```{r}
summary(raw_data_2015)
```

```{r}
str(raw_data_2015)
```

```{r}
levels(raw_data_2015$CLASE)
```

```{r}
levels(raw_data_2015$CLASE) <- c("Otro","Atropello","Caida_Ocupante","Caida_Ocupante","Choque",
                                 "Incendio","Otro","Volcamiento")
```

```{r}
levels(raw_data_2015$CLASE)
```

### Datos 2016

```{r}
raw_data_2016 <- read.csv(file="./data/Accidentalidad_georreferenciada_2016.csv", encoding="UTF-8", header=TRUE, sep=",")
```


```{r}
head(raw_data_2016)
str(raw_data_2016)
```


```{r}
levels(raw_data_2016$CLASE)
```

```{r}
levels(raw_data_2016$CLASE) <- c("Otro","Atropello","Caida_Ocupante","Caida_Ocupante","Choque",
                                 "Incendio","Otro","Volcamiento")
```

```{r}
levels(raw_data_2016$CLASE)
```


### Datos 2017

```{r}
raw_data_2017 <- read.csv(file="./data/Accidentalidad_georreferenciada_2017.csv", encoding="UTF-8", header=TRUE, sep=",")
```


```{r}
head(raw_data_2017)
str(raw_data_2017)
```


```{r}
levels(raw_data_2017$CLASE)
```

```{r}
levels(raw_data_2017$CLASE) <- c("Atropello","Caida_Ocupante","Caida_Ocupante","Choque","Choque",
                                 "Otro","Incendio","Otro","Volcamiento")
```

```{r}
levels(raw_data_2017$CLASE)
```

```{r}
levels(raw_data_2017$CLASE)
```

```{r}
summary(raw_data_2014$CLASE)
```

```{r}
summary(raw_data_2015$CLASE)
```

```{r}
summary(raw_data_2016$CLASE)
```

```{r}
summary(raw_data_2017$CLASE)
```


```{r}
raw_data_2018 <- read.csv(file="./data/Accidentalidad_georreferenciada_2018.csv", encoding="UTF-8", header=TRUE, sep=",")
```

```{r}
str(raw_data_2018)
```

```{r}
levels(raw_data_2018$CLASE)
```

```{r}
levels(raw_data_2018$CLASE) <- c("Atropello","Caida_Ocupante","Caida_Ocupante","Choque","Incendio","Otro", "Volcamiento")
```

```{r}
levels(raw_data_2018$CLASE)
```


```{r}
summary(raw_data_2018$CLASE)
```


### Unir los datos

```{r}
Total_Dataset <- rbind(raw_data_2014,raw_data_2015,raw_data_2016, raw_data_2017, raw_data_2018)
```

```{r}
str(Total_Dataset)
```

```{r}
levels(Total_Dataset$CLASE)
```

```{r}
summary(Total_Dataset$CLASE)
```

La Fecha está cargada como factor, se realiza una transformación a formato de fecha (date)


```{r}
Total_Dataset$FECHA <- as.Date(Total_Dataset$FECHA, format="%Y-%m-%d")
tail(Total_Dataset)
```






# ANALISIS DESCRIPTIVO

```{r}
library(plyr)
library(dplyr)
Datos_Diarios=Total_Dataset%>%group_by(FECHA)%>%summarise(conteo=n())
```


```{r message=FALSE}
library(plotly)
plot_ly (data=subset(Datos_Diarios,subset = (FECHA<="2017-12-31")),
         x = ~FECHA,
         y = ~conteo,
         type = "scatter" ,mode = "lines",
         line=list(width=1))%>%
  layout(title='Choques Diarios',
         xaxis=list(title="Día"),
         yaxis=list(title="Número de choques"))
```

# EVALUACIÓN DE MODELOS



# ELECCIÓN DEL MODELO





